### ISSUE TITLE
Parsing UUID v4 without hyphens

### ISSUE THREAD

**Issue by albe-jj** [daegalus/dart-uuid#105]
I need to read UUIDs v4 from a database where an SQLAlchemy applicaiton stores them without hyphens. 
`  print(UuidParsing.parse('797ff04311eb11e180d6510998755d10').toString());`
throws validation error. Is there a way to have uuids without hyphens parsed correctly by this package?

**Comment by daegalus** [comment]
I will try to look into this sometime this week. I think I might be able to support this with some options.

**Comment by daegalus** [comment]
So double checking my code, my parsing logic doesn't care if hyphens are present or not. Only my validator does. You can disable validation for now until I get a fix in by passing `validate: false` as a parameter to `parse`

**Comment by albe-jj** [comment]
Ok thanks for the response. Since I'm using it for database operation all I want is to compare strings, so for now this will get me going
```
print(UuidValue.fromList(UuidParsing.parse('797ff04311eb11e180d6510998755d10', validate: false)).toString());
returns ->797ff043-11eb-11e1-80d6-510998755d10
```

**Comment by daegalus** [comment]
This should now be fixed in 4.3.1, there is now a `noDashes` parameter on parse and validation functions (same for UuidValue)

**Comment by albe-jj** [comment]
running version 4.3.1 but still get error when running
`   print(UuidValue.fromList(UuidParsing.parse('797ff04311eb11e180d6510998755d10', validate:true)).toString());`
```Unhandled exception:
FormatException: The provided UUID is invalid.
797ff04311eb11e180d6510998755d10
#0      UuidValidation.isValidOrThrow (package:uuid/validation.dart:84:7)
#1      UuidParsing.parse (package:uuid/parsing.dart:51:22)
#2      main (package:qdrive_local_dart/src/test_uuid.dart:9:40)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Also not sure if it's the intended behavior but when I run 
`  print(UuidValue.fromString('797ff04311eb11e180d6510998755d10').toString());`
I get 
 `797ff04311eb11e180d6510998755d10`

so to get the uuid formatted as a string with the hyphen I need to run 
`  print(UuidValue.fromList(UuidParsing.parse('797ff04311eb11e180d6510998755d10', validate: false)).toString());`
which returns correctly `797ff043-11eb-11e1-80d6-510998755d10`

**Comment by daegalus** [comment]
Sorry, just saw this, been swamped. That is unexpected expected behavior. As I don't format on toString. It just returns whatever the string value is inside UuidValue. Before we only allowed hyphens so it made.sense that I don't need to format.

I will add a toFormattedString() in the next few days to handle this case.

**Comment by daegalus** [comment]
4.3.2 adds the new function
